<a href="https://colab.research.google.com/github/Yuliia-Safonova/DTA-2026/blob/main/Homework/Numpy_homework_27_05_2026.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 🏠 Домашнє завдання — NumPy

**До тьюторіалу:** Pandas + Matplotlib: Аналіз даних з нуля

---
### Правила виконання
- Кожне завдання виконуй в окремій клітинці
- Не використовуй цикли там де можна обійтись операціями NumPy
- Після виконання — запусти клітинку і перевір що результат виглядає правильно
- Якщо застряг — поверніться до відповідного розділу тьюторіалу

**Оцінювання:** кожне завдання — 1 бал. Фінальний проєкт — 3 бали. Всього: **14 балів**

---

## Розділ 1 — Масиви ndarray та атрибути

> **Що повторюємо:** `np.array()`, `np.zeros()`, `np.ones()`, `np.arange()`, `np.linspace()`,
> атрибути `.shape`, `.ndim`, `.size`, `.dtype`

### ✏️ Завдання 1.1

У тебе є дані середньомісячних температур у Харкові за рік (°C):

```
-5, -4, 2, 10, 17, 21, 23, 22, 16, 9, 2, -3
```

1. Створи NumPy масив із цих значень і назви його `temps`
2. Виведи масив
3. Виведи: кількість вимірів (`ndim`), форму (`shape`), кількість елементів (`size`), тип даних (`dtype`)
4. Виведи мінімальну, максимальну температуру та середньорічну (округли до 1 знаку)

In [1]:
import numpy as np

# Твій код:

temps = np.array([-5, -4, 2, 10, 17, 21, 23, 22, 16, 9, 2, -3])
print("Масив температур:")
print(temps)

print()
print("Кількість вимірів:", temps.ndim)
print("Форма масиву:", temps.shape)
print("Кількість елементів:", temps.size)
print("Тип даних:", temps.dtype)

print()
print("Мінімальна температура:", temps.min())
print("Максимальна температура:", temps.max())
print("Середньорічна температура:", round(temps.mean(), 1))

Масив температур:
[-5 -4  2 10 17 21 23 22 16  9  2 -3]

Кількість вимірів: 1
Форма масиву: (12,)
Кількість елементів: 12
Тип даних: int64

Мінімальна температура: -5
Максимальна температура: 23
Середньорічна температура: 9.2


### ✏️ Завдання 1.2

Створи таблицю планових продажів для 3 менеджерів на 4 квартали.

1. Створи матрицю `plan` розміром **3×4**, заповнену значенням `50` (тис. грн) — використай `np.full()`
2. Виведи матрицю
3. Виведи її форму та загальну кількість елементів
4. Створи другу матрицю `bonus` розміром **3×4** із нулів — менеджери ще не отримали бонусів
5. Виведи суму `plan + bonus` і переконайся що вона рівна `plan`

In [2]:
# Твій код:
plan = np.full((3, 4), 50)

print("План продажів:")
print(plan)

print("\nФорма матриці:", plan.shape)
print("Кількість елементів:", plan.size)

bonus = np.zeros((3, 4))
print("\nБонуси:")
print(bonus)

total = plan + bonus
print("\nPlan + Bonus:")
print(total)

План продажів:
[[50 50 50 50]
 [50 50 50 50]
 [50 50 50 50]]

Форма матриці: (3, 4)
Кількість елементів: 12

Бонуси:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Plan + Bonus:
[[50. 50. 50. 50.]
 [50. 50. 50. 50.]
 [50. 50. 50. 50.]]


---
## Розділ 2 — Індексація та зрізи

> **Що повторюємо:** індексація 1D і 2D масивів, зрізи `[start:stop:step]`,
> вибір рядків та стовпців матриці

### ✏️ Завдання 2.1

Є масив денних продажів магазину за 2 тижні (14 днів):

```python
sales = np.array([320, 415, 290, 480, 350, 620, 580,
                  310, 440, 305, 510, 370, 650, 595])
```

Виконай такі вибірки **без циклів**, лише через зрізи:
1. Продажі першого тижня (дні 1–7)
2. Продажі другого тижня (дні 8–14)
3. Продажі у вихідні: 6-й, 7-й, 13-й, 14-й день — використай індексацію списком `[[5,6,12,13]]`
4. Продажі через день, починаючи з першого (непарні дні: 1, 3, 5...)
5. Масив у зворотному порядку

In [3]:
sales = np.array([320, 415, 290, 480, 350, 620, 580,
                  310, 440, 305, 510, 370, 650, 595])

# Твій код:
print("Продажі першого тиждня:")
print(sales[:7])

print("\nПродажі другого тиждня:")
print(sales[7:])

print("\nПродажі у вихідні:")
print(sales[[5, 6, 12, 13]])

print("\nПродажі у непарні дні:")
print(sales[::2])

print("\nМасив у зворотному порядку:")
print(sales[::-1])

Продажі першого тиждня:
[320 415 290 480 350 620 580]

Продажі другого тиждня:
[310 440 305 510 370 650 595]

Продажі у вихідні:
[620 580 650 595]

Продажі у непарні дні:
[320 290 350 580 440 510 650]

Масив у зворотному порядку:
[595 650 370 510 305 440 310 580 620 350 480 290 415 320]


### ✏️ Завдання 2.2

Є матриця оцінок студентів: **4 студенти × 5 предметів**.

```python
grades = np.array([
    [85, 72, 91, 78, 88],   # Олена
    [63, 88, 74, 95, 70],   # Максим
    [90, 65, 82, 70, 94],   # Аня
    [75, 80, 68, 85, 79],   # Богдан
])
```

1. Виведи всі оцінки Олени (перший рядок)
2. Виведи оцінки всіх студентів з 3-го предмету (третій стовпець)
3. Виведи підматрицю: оцінки Максима та Ані з предметів 2–4 (рядки 1–2, стовпці 1–3)
4. Виведи оцінки останнього студента з останнього предмету

In [4]:
grades = np.array([
    [85, 72, 91, 78, 88],
    [63, 88, 74, 95, 70],
    [90, 65, 82, 70, 94],
    [75, 80, 68, 85, 79],
])

# Твій код:

# Виведи всі оцінки Олени
print("Оцінки Олени:")
print(grades[0,:])

# Виведи оцінки всіх студентів з 3-го предмету
print("\nОцінки з 3-го предмету:")
print(grades[:, 2])

# Виведи підматрицю: оцінки Максима та Ані з предметів 2–4
print("\nОцінки Максима та Ані:")
print(grades[1:3, 1:4])

# Виведи оцінки останнього студента з останнього предмету
print("\nОцінки Богдана з останнього предмету:")
print(grades[-1, -1])

Оцінки Олени:
[85 72 91 78 88]

Оцінки з 3-го предмету:
[91 74 82 68]

Оцінки Максима та Ані:
[[88 74 95]
 [65 82 70]]

Оцінки Богдана з останнього предмету:
79


---
## Розділ 3 — Математичні операції та векторизація

> **Що повторюємо:** арифметика з масивами, `np.sqrt()`, `np.round()`,
> агрегатні функції `.sum()`, `.mean()`, `.std()`, `.min()`, `.max()`, `np.median()`

### ✏️ Завдання 3.1

Є масив цін товарів у доларах. Виконай **без циклів**:

```python
prices_usd = np.array([15.99, 42.50, 8.00, 125.00, 33.75, 67.20, 9.99])
```

1. Переведи ціни в гривні (курс: **1 USD = 41.5 UAH**), результат округли до 2 знаків
2. Нарахуй ПДВ 20% — помнож гривневі ціни на 1.2, округли до 2 знаків
3. Знайди: мінімальну, максимальну, середню ціну з ПДВ
4. Знайди суму всіх товарів з ПДВ — це загальна вартість кошика
5. Виведи результати з поясненнями

In [5]:
prices_usd = np.array([15.99, 42.50, 8.00, 125.00, 33.75, 67.20, 9.99])

# Твій код:

# Переведи ціни в гривні (курс: 1 USD = 41.5 UAH), результат округли до 2 знаків
prices_uah = np.round(prices_usd * 41.5, 2)
print("Ціни в гривні, UAH:")
print(prices_uah)

# Нарахуй ПДВ 20% — помнож гривневі ціни на 1.2, округли до 2 знаків
prices_vat = np.round(prices_uah * 1.2, 2)
print("\nЦіни з ПДВ 20%, грн.:")
print(prices_vat)

# Знайди: мінімальну, максимальну, середню ціну з ПДВ
print("\nМінімальна ціна з ПДЗ:", prices_vat.min())
print("Максимальна ціна з ПДЗ:", prices_vat.max())
print("Середня ціна з ПДЗ:", round(prices_vat.mean(), 2))

# Знайди суму всіх товарів з ПДВ — це загальна вартість кошика
print("\nСума всіх товарів з кошика:", prices_vat.sum())


Ціни в гривні, UAH:
[ 663.58 1763.75  332.   5187.5  1400.62 2788.8   414.58]

Ціни з ПДВ 20%, грн.:
[ 796.3  2116.5   398.4  6225.   1680.74 3346.56  497.5 ]

Мінімальна ціна з ПДЗ: 398.4
Максимальна ціна з ПДЗ: 6225.0
Середня ціна з ПДЗ: 2151.57

Сума всіх товарів з кошика: 15061.0


### ✏️ Завдання 3.2

Є дані про кількість товарів на складі та їх собівартість.
Виконай **без циклів**:

```python
quantity  = np.array([120, 45, 300, 18, 75, 200, 60])
cost_each = np.array([250, 1800, 45, 9500, 380, 120, 750])
names     = ['Кабель', 'Клавіатура', 'Зошит', 'Монітор',
             'Мишка', 'Ручка', 'Навушники']
```

1. Порахуй загальну вартість кожного товару на складі (`quantity * cost_each`)
2. Знайди загальну вартість всього складу
3. Знайди товар з найбільшою сумарною вартістю — використай `np.argmax()`
4. Знайди товар з найменшою сумарною вартістю — `np.argmin()`
5. Виведи середню вартість одного найменування на складі

In [6]:
quantity  = np.array([120, 45, 300, 18, 75, 200, 60])
cost_each = np.array([250, 1800, 45, 9500, 380, 120, 750])
names     = ['Кабель', 'Клавіатура', 'Зошит', 'Монітор',
             'Мишка', 'Ручка', 'Навушники']

# Твій код:

# Порахуй загальну вартість кожного товару на складі (quantity * cost_each)
total_cost = quantity * cost_each
print("Загальна вартість кожного товару:")
print(total_cost)

# Знайди загальну вартість всього складу
warehouse_total = total_cost.sum()
print("\nЗагальна вартість всього складу:", warehouse_total, "грн.")

# Знайди товар з найбільшою сумарною вартістю — використай np.argmax()
max_index = np.argmax(total_cost)
print("\nТовар з найбільшою сумарною вартістю:")
print(names[max_index], "-", total_cost[max_index], "грн.")

# Знайди товар з найменшою сумарною вартістю — np.argmin()
min_index = np.argmin(total_cost)
print("\nТовар з найменьшою сумарною вартістю:")
print(names[min_index], "-", total_cost[min_index], "грн.")

# Виведи середню вартість одного найменування на складі
print("\nСередня вартість одного товару:", round(total_cost.mean(), 2), "грн.")

Загальна вартість кожного товару:
[ 30000  81000  13500 171000  28500  24000  45000]

Загальна вартість всього складу: 393000 грн.

Товар з найбільшою сумарною вартістю:
Монітор - 171000 грн.

Товар з найменьшою сумарною вартістю:
Зошит - 13500 грн.

Середня вартість одного товару: 56142.86 грн.


---
## Розділ 4 — Булеве маскування і фільтрація

> **Що повторюємо:** булеві маски, фільтрація `arr[mask]`,
> `np.where()`, `.sum()` для підрахунку True

### ✏️ Завдання 4.1

Є масив часу виконання замовлень у хвилинах (норма — до 30 хв):

```python
delivery_time = np.array([22, 35, 28, 41, 19, 55, 27, 33, 24, 48,
                           31, 26, 52, 18, 29, 38, 23, 44, 20, 36])
```

1. Знайди всі замовлення, виконані **вчасно** (≤ 30 хв)
2. Знайди всі **запізнілі** замовлення (> 30 хв)
3. Порахуй кількість вчасних і запізнілих
4. Знайди відсоток запізнілих замовлень (округли до 1 знаку)
5. Яка середня затримка серед запізнілих замовлень?

In [7]:
delivery_time = np.array([22, 35, 28, 41, 19, 55, 27, 33, 24, 48,
                           31, 26, 52, 18, 29, 38, 23, 44, 20, 36])

# Твій код:

# Знайди всі замовлення, виконані вчасно (≤ 30 хв)
on_time = delivery_time[delivery_time <= 30]
print("Вчасні замовлення:")
print(on_time)

# Знайди всі запізнілі замовлення (> 30 хв)
late = delivery_time[delivery_time > 30]
print("\nЗапізнілі замовлення:")
print(late)

# Порахуй кількість вчасних і запізнілих
print("\nКількість вчасних замовлень:", on_time.size)
print("\nКількість запізнілих замовлень:", late.size)

# Знайди відсоток запізнілих замовлень (округли до 1 знаку)
print("\nВідсоток запізнілих замовлень", round((late.size / delivery_time.size) * 100, 1), "%")

# Яка середня затримка серед запізнілих замовлень?
print("\nСередня затримка:", (late - 30).mean(), "хв.")

Вчасні замовлення:
[22 28 19 27 24 26 18 29 23 20]

Запізнілі замовлення:
[35 41 55 33 48 31 52 38 44 36]

Кількість вчасних замовлень: 10

Кількість запізнілих замовлень: 10

Відсоток запізнілих замовлень 50.0 %

Середня затримка: 11.3 хв.


### ✏️ Завдання 4.2

Є масив щоденних продажів за місяць. Використай `np.where()`:

```python
np.random.seed(42)
daily = np.random.randint(100, 900, size=30)
```

1. Знайди дні з продажами **вище середнього** за місяць
2. Порахуй скільки таких днів
3. За допомогою `np.where()` створи масив `status`:
   - `'Гарний день'` — якщо продажі вище середнього
   - `'Звичайний день'` — якщо нижче або рівно
4. Виведи перші 10 днів: продажі та їх статус поряд

In [8]:
np.random.seed(42)
daily = np.random.randint(100, 900, size=30)

# Твій код:
print("Продажі за місяць:")
print(daily)

# Знайди дні з продажами вище середнього за місяць
avg_sales = daily.mean()
print("\nДні з продажами вище середнього:")
print(daily[daily > avg_sales])

# Порахуй скільки таких днів
print("\nКількість днів вище середнього:", daily[daily > avg_sales].size)

# За допомогою np.where() створи масив status:
    #   'Гарний день' — якщо продажі вище середнього
    #   'Звичайний день' — якщо нижче або рівно
status = np.where(daily > avg_sales, 'Гарний день', 'Звичайний день')
print("\nСтатуси днів:")
print(status)

# Виведи перші 10 днів: продажі та їх статус поряд
print("\nПерші 10 днів:")

for i in range(10):
    print(f"День {i+1}: продажі = {daily[i]}, статус - {status[i]}")


Продажі за місяць:
[202 535 370 206 171 800 120 714 221 566 314 430 558 187 472 199 763 230
 761 408 869 443 591 513 485 291 376 260 559 413]

Дні з продажами вище середнього:
[535 800 714 566 558 472 763 761 869 443 591 513 485 559]

Кількість днів вище середнього: 14

Статуси днів:
['Звичайний день' 'Гарний день' 'Звичайний день' 'Звичайний день'
 'Звичайний день' 'Гарний день' 'Звичайний день' 'Гарний день'
 'Звичайний день' 'Гарний день' 'Звичайний день' 'Звичайний день'
 'Гарний день' 'Звичайний день' 'Гарний день' 'Звичайний день'
 'Гарний день' 'Звичайний день' 'Гарний день' 'Звичайний день'
 'Гарний день' 'Гарний день' 'Гарний день' 'Гарний день' 'Гарний день'
 'Звичайний день' 'Звичайний день' 'Звичайний день' 'Гарний день'
 'Звичайний день']

Перші 10 днів:
День 1: продажі = 202, статус - Звичайний день
День 2: продажі = 535, статус - Гарний день
День 3: продажі = 370, статус - Звичайний день
День 4: продажі = 206, статус - Звичайний день
День 5: продажі = 171, статус - Звича

---
## Розділ 5 — reshape та сортування

> **Що повторюємо:** `.reshape()`, `.flatten()`, `np.sort()`, `np.argsort()`

### ✏️ Завдання 5.1

Є 1D масив з 24 показників продажів (по годинах за добу):

```python
hourly = np.array([12, 8, 5, 3, 4, 9, 18, 35, 52, 61, 58, 64,
                   70, 67, 55, 48, 53, 62, 74, 68, 45, 30, 22, 15])
```

1. Перетвори масив у матрицю **6×4** (6 блоків по 4 години) і виведи
2. Знайди суму продажів у кожному 4-годинному блоці (по рядках)
3. Відсортуй вихідний 1D масив за **зростанням** і виведи
4. Знайди **індекси** годин відсортованих за зростанням продажів — `np.argsort()`
5. Виведи топ-3 найпродуктивніших години (їхні номери, рахуючи з 0)

In [15]:
hourly = np.array([12, 8, 5, 3, 4, 9, 18, 35, 52, 61, 58, 64,
                   70, 67, 55, 48, 53, 62, 74, 68, 45, 30, 22, 15])

# Твій код:

# Перетвори масив у матрицю 6×4 (6 блоків по 4 години) і виведи
matrix = hourly.reshape(6, 4)
print("Matrix 6*4:")
print(matrix)

# Знайди суму продажів у кожному 4-годинному блоці (по рядках)
row_sums = matrix.sum(axis=1)
print("\nTotal for each row:")
print(row_sums)

# Відсортуй вихідний 1D масив за зростанням і виведи
sorted_hourly = np.sort(hourly)
print("\nMassive growth:")
print(sorted_hourly)

# Знайди індекси годин відсортованих за зростанням продажів — np.argsort()
sorted_index = np.argsort(hourly)
print("\nIndexes hours after sorting:")
print(sorted_index)

# Виведи топ-3 найпродуктивніших години (їхні номери, рахуючи з 0)
top3_index = np.argsort(hourly)[-3:][::-1]
print("\nTop 3 most productive hours:")
print(top3_index)

Matrix 6*4:
[[12  8  5  3]
 [ 4  9 18 35]
 [52 61 58 64]
 [70 67 55 48]
 [53 62 74 68]
 [45 30 22 15]]

Total for each row:
[ 28  66 235 240 257 112]

Massive growth:
[ 3  4  5  8  9 12 15 18 22 30 35 45 48 52 53 55 58 61 62 64 67 68 70 74]

Indexes hours after sorting:
[ 3  4  2  1  5  0 23  6 22 21  7 20 15  8 16 14 10  9 17 11 13 19 12 18]

Top 3 most productive hours:
[18 12 19]


---
## Розділ 6 — Генерація випадкових чисел

> **Що повторюємо:** `np.random.seed()`, `np.random.randint()`,
> `np.random.normal()`, `np.random.choice()`

### ✏️ Завдання 6.1

Змоделюй результати маркетингового опитування 50 клієнтів.

1. Встанови `np.random.seed(99)`
2. Згенеруй масив `ages` — вік 50 клієнтів: цілі числа від 18 до 65
3. Згенеруй масив `scores` — оцінки задоволеності (нормальний розподіл, середнє=7, σ=1.5), округли до 1 знаку
4. Обріж `scores` так щоб значення були від 1 до 10 — `np.clip(arr, 1, 10)`
5. Виведи:
   - середній вік клієнтів
   - середню оцінку задоволеності
   - кількість клієнтів з оцінкою >= 8 («задоволені»)
   - відсоток задоволених

In [10]:
# Твій код:

# Встанови np.random.seed(99)
np.random.seed(99)

# Згенеруй масив ages — вік 50 клієнтів: цілі числа від 18 до 65
ages = np.random.randint(18, 66, size=50)

# Згенеруй масив scores — оцінки задоволеності (нормальний розподіл, середнє=7, σ=1.5), округли до 1 знаку
scores = np.random.normal(loc=7, scale=1.5, size=50)
scores = np.round(scores, 1)

# Обріж scores так щоб значення були від 1 до 10 — np.clip(arr, 1, 10)
scores = np.clip(scores, 1, 10)

# Виведи:
    # середній вік клієнтів
avg_age = round(ages.mean(), 1)

    # середню оцінку задоволеності
avg_score = round(scores.mean(), 1)

    # кількість клієнтів з оцінкою >= 8 («задоволені»)
satisfied_count = np.sum(scores >= 8)

    # відсоток задоволених
satisfied_percent = round((satisfied_count / scores.size) * 100, 1)

print("Age of customers:")
print(ages)

print("\nSatisfaction ratings:")
print(scores)

print("\nAverage age:", avg_age)

print("\nAverage rating:", avg_score)

print("\nNumber of satisfied customers:", satisfied_count)

print("\nPercentage of satisfied customers:", satisfied_percent, "%")

Age of customers:
[19 53 58 27 58 36 22 23 19 41 53 19 47 56 61 41 20 18 30 58 26 38 57 33
 65 45 55 64 54 62 35 27 50 39 65 59 53 37 40 44 23 30 50 45 19 62 29 29
 47 49]

Satisfaction ratings:
[ 5.7  6.4  5.7  9.2  5.5  6.1  6.8  7.9  4.8  8.8  7.5  6.4  7.2  6.2
  6.7  7.4  6.   4.7  7.1  5.   5.4  5.6  8.   8.5  9.1  9.6  7.1  7.1
  7.4  7.8  6.7  7.1  7.3  5.5  6.7  5.5  7.9  8.3  4.9  6.2 10.   4.8
  7.6  4.7  6.5  4.2  7.7  7.7  9.4  8. ]

Average age: 41.8

Average rating: 6.9

Number of satisfied customers: 10

Percentage of satisfied customers: 20.0 %


---
## 🏆 Фінальний проєкт — Аналіз даних магазину

> **Використовуємо все з тьюторіалу разом**

Ти аналітик даних невеликого магазину електроніки.
Тобі передали масив продажів за 8 тижнів (56 днів).

Виконай повний аналіз та дай відповіді на запитання керівника.

In [11]:
# Дані — не змінюй цю клітинку
np.random.seed(2024)
base = np.random.randint(200, 800, 56)

# Вихідні продаються краще
weekend_boost = np.array([1 if i % 7 in [5, 6] else 0 for i in range(56)])
sales_56 = (base + weekend_boost * np.random.randint(100, 300, 56)).astype(int)

print('Дані отримано. Масив sales_56 готовий до аналізу.')
print(f'Елементів: {sales_56.size}, форма: {sales_56.shape}')


Дані отримано. Масив sales_56 готовий до аналізу.
Елементів: 56, форма: (56,)


### Запитання 1 — Загальна статистика (Розділ 1, 3)
Виведи:
- Загальна виручка за 56 днів
- Середньоденна виручка (округли до 2 знаків)
- Мінімальний та максимальний денний продаж
- Стандартне відхилення (наскільки продажі «скачуть»)

In [12]:
# Твій код:

# Загальна виручка за 56 днів
print(f"Загальна виручка за 56 днів: {np.sum(sales_56)} грн.\n")

# Середньоденна виручка (округли до 2 знаків)
print(f"Середньоденна виручка: {np.mean(sales_56):.2f} грн.\n")

# Мінімальний та максимальний денний продаж
print(f"Мінімальний денний продаж: {np.min(sales_56)} грн.\n")
print(f"Максимальний денний продаж: {np.max(sales_56)} грн.\n")

# Стандартне відхилення (наскільки продажі «скачуть»)
print(f"Стандартне відхилення продажів: {np.std(sales_56):.2f}")

Загальна виручка за 56 днів: 31819 грн.

Середньоденна виручка: 568.20 грн.

Мінімальний денний продаж: 222 грн.

Максимальний денний продаж: 1072 грн.

Стандартне відхилення продажів: 195.52


### Запитання 2 — Тижневий аналіз (Розділ 5)
1. Перетвори `sales_56` у матрицю **8×7** (8 тижнів по 7 днів)
2. Знайди виручку кожного тижня (сума по рядках)
3. Знайди найкращий тиждень і виведи його номер (рахуючи з 1) та суму
4. Знайди середньоденну виручку по кожному дню тижня (середнє по стовпцях)
5. Виведи який день тижня в середньому найприбутковіший (0=Пн, 6=Нд)

In [16]:
# Твій код:

# Перетвори sales_56 у матрицю 8×7 (8 тижнів по 7 днів)
matrix = sales_56.reshape(8, 7)
print("Матриця продажів 8x7:")
print(matrix)

# Знайди виручку кожного тижня (сума по рядках)
weekly_revenue = matrix.sum(axis=1)
print("\nВиручка кожного тижня:")
print(weekly_revenue)

# Знайди найкращий тиждень і виведи його номер (рахуючи з 1) та суму
best_week_sum = weekly_revenue.max()
best_week_index = weekly_revenue.argmax()

print(f"\nНайкращий тиждень {best_week_index + 1} - сума продажів = {best_week_sum} грн.")

# Знайди середньоденну виручку по кожному дню тижня (середнє по стовпцях)
daily_avg = matrix.mean(axis=0)
print(f"\nСередньоденна виручка по днях тижня: {daily_avg.round(2)}")

# Виведи який день тижня в середньому найприбутковіший (0=Пн, 6=Нд)
days = ['Понеділок', 'Вівторок', 'Середа', 'Четвер', 'П’ятниця', 'Субота', 'Неділя']
best_day_sum = daily_avg.max()
best_day_index = daily_avg.argmax()

print(f"\nВ середньому найприбутковіший день тижня: {days[best_day_index]}")

Матриця продажів 8x7:
[[ 706  739  748  646  383  556  777]
 [ 427  274  522  680  708  465  845]
 [ 447  402  551  567  723  404  469]
 [ 254  314  383  754  297  472 1072]
 [ 773  510  769  798  510  824  852]
 [ 336  297  591  637  296  735  408]
 [ 661  447  734  558  339  710  779]
 [ 559  661  229  222  454  872  673]]

Виручка кожного тижня:
[4555 3921 3563 3546 5036 3300 4228 3670]

Найкращий тиждень 5 - сума продажів = 5036 грн.

Середньоденна виручка по днях тижня: [520.38 455.5  565.88 607.75 463.75 629.75 734.38]

В середньому найприбутковіший день тижня: Неділя


### Запитання 3 — Фільтрація та маскування (Розділ 4)
1. Знайди кількість **«слабких» днів** — продажі нижче 400 грн
2. Знайди кількість **«сильних» днів** — продажі вище 700 грн
3. Яка середня виручка у слабкі дні і яка у сильні?
4. Створи масив `labels` за допомогою `np.where()`:
   - `'Слабкий'` якщо < 400
   - `'Сильний'` якщо > 700
   - `'Нормальний'` в решті випадків (підказка: вкладений `np.where`)
5. Виведи перші 14 днів: продажі та їх мітки

In [14]:
# Твій код:

# Знайди кількість «слабких» днів — продажі нижче 400 грн
weak_days = sales_56 < 400
print(f"Кількість «слабких» днів (продажі нижче 400 грн) - {weak_days.sum()}\n")

# Знайди кількість «сильних» днів — продажі вище 700 грн
strong_days = sales_56 > 700
print(f"Кількість «сильних» днів — продажі вище 700 грн - {strong_days.sum()}\n")

# Яка середня виручка у слабкі дні і яка у сильні?
weak_avg = sales_56[weak_days].mean()
strong_avg = sales_56[strong_days].mean()

print(f"Середня виручка у слабкі дні: {weak_avg:.2f}")
print(f"Середня виручка у сильні дні: {strong_avg:.2f}\n")

# Створи масив labels за допомогою np.where():
        # 'Слабкий' якщо < 400
        # 'Сильний' якщо > 700
        # 'Нормальний' в решті випадків (підказка: вкладений np.where)

labels = np.where(sales_56 < 400, 'слабкий',
                  np.where(sales_56 > 700, 'сильний', 'нормальний'))
print("Масив labels:\n", labels)

# Виведи перші 14 днів: продажі та їх мітки

print("\nПерші 14 днів продажів\n")
for i in range(14):
    print(f"{i+1} день: продажі = {sales_56[i]} грн., {labels[i]} день")


Кількість «слабких» днів (продажі нижче 400 грн) - 12

Кількість «сильних» днів — продажі вище 700 грн - 19

Середня виручка у слабкі дні: 302.00
Середня виручка у сильні дні: 785.16

Масив labels:
 ['сильний' 'сильний' 'сильний' 'нормальний' 'слабкий' 'нормальний'
 'сильний' 'нормальний' 'слабкий' 'нормальний' 'нормальний' 'сильний'
 'нормальний' 'сильний' 'нормальний' 'нормальний' 'нормальний'
 'нормальний' 'сильний' 'нормальний' 'нормальний' 'слабкий' 'слабкий'
 'слабкий' 'сильний' 'слабкий' 'нормальний' 'сильний' 'сильний'
 'нормальний' 'сильний' 'сильний' 'нормальний' 'сильний' 'сильний'
 'слабкий' 'слабкий' 'нормальний' 'нормальний' 'слабкий' 'сильний'
 'нормальний' 'нормальний' 'нормальний' 'сильний' 'нормальний' 'слабкий'
 'сильний' 'сильний' 'нормальний' 'нормальний' 'слабкий' 'слабкий'
 'нормальний' 'сильний' 'нормальний']

Перші 14 днів продажів

1 день: продажі = 706 грн., сильний день
2 день: продажі = 739 грн., сильний день
3 день: продажі = 748 грн., сильний день
4 день:

---
## ✅ Підсумок

| Розділ | Завдання | Балів | Виконано |
|--------|----------|-------|----------|
| 1 — Масиви ndarray | 1.1, 1.2 | 2 | ☐ |
| 2 — Індексація та зрізи | 2.1, 2.2 | 2 | ☐ |
| 3 — Математичні операції | 3.1, 3.2 | 2 | ☐ |
| 4 — Булеве маскування | 4.1, 4.2 | 2 | ☐ |
| 5 — reshape та сортування | 5.1 | 1 | ☐ |
| 6 — Генерація випадкових | 6.1 | 1 | ☐ |
| 🏆 Фінальний проєкт | Питання 1–3 | 3 | ☐ |
| **Разом** | | **13** | |
